### ISSUE TITLE
What is a site?

### ISSUE THREAD

**Issue by thomasheartman** [enonic/guide-quickstart#4]
The section [Creating a site from scratch](https://developer.enonic.com/guides/headless-cms-intro#creating_a_site_from_scratch) talks about creating a new site from scratch, but the documentation doesn't mention what a site is anywhere. Sites have also been alluded to a number of times previously, but never explained. 

As someone new to the system, it's not clear exactly what a site is. In the case of APIs, is it just the base URL that changes? [This entry in the Content Studio reference docs](https://developer.enonic.com/docs/content-studio/stable/content-types#site_content) goes some way towards explaining what they are, but it doesn't clarify what happens if you put multiple sites at the root (or why you might (not) want to do that), nor does it say anything about placing sites further down in the hierarchy. It mentions that 'sites are usually created at the root level', but doesn't say why that is. 

Admittedly, I'm not really sure what a site is myself (after XP dev 101, 201 and Content 101 courses). Is it just a convenient grouping? Do you need a site? 

Anyway, this is deviating a bit from the headless starter docs (but might be something to consider for the Content Studio docs?), so to refocus:

I think the Headless Starter docs should point to the reference docs, saying something like 'A site is how you usually group content in Content Studio. To learn more, visit the [reference docs](https://developer.enonic.com/docs/content-studio/stable/content-types#site_content)'.

**Comment by sigdestad** [comment]
Removed this section from quickstart guide
